Repository datenanfragen/website, pull requests merged in 2019-10, with the labels that each got.

#102 Fix bug where requests would fail if no template was available for a specific locale
  src/Components/RequestGeneratorBuilder.js
  src/Utility/errors.js
  src/Utility/requests.js
  src/i18n/de.json
  src/i18n/en.json
Labels: bug

#166 Fixes #142: Add act page for Ada Health
  content/act/ada-health.de.md
Labels: content

#159 Add email type
  src/Components/Generator/DynamicInput.js
  src/Components/Generator/DynamicInputContainer.js
  src/Components/RequestGeneratorBuilder.js
  src/Utility/RequestLetter.js
  src/Utility/SavedIdData.js
  src/Utility/requests.js
  src/i18n/de.json
  src/i18n/en.json
  src/id-data-controls.js
Labels: feature
