Repository datenanfragen/website, pull requests merged in 2020-08, with the labels that each got.

#345 Translate 'Territorial scope' blog post into English
  content/en/blog/gdpr-territorial-scope/gdpr-territorial-scope.jpg
  content/en/blog/gdpr-territorial-scope/index.md
Labels: content

#335 Transparency page updates: Re-add old info, sensible ordering and compensated lectures
  content/de/verein/transparency.md
  content/en/verein/transparency.md
  content/fr/verein/transparency.md
Labels: content

#323 Update sample letters as per datenanfragen/data#562
  content/de/blog/sample-letter-gdpr-access-request/index.md
  content/de/blog/sample-letter-gdpr-direct-marketing-objection/index.md
  content/de/blog/sample-letter-gdpr-erasure-request/index.md
  content/de/blog/sample-letter-gdpr-rectification-request/index.md
  content/en/blog/sample-letter-gdpr-access-request/index.md
  content/en/blog/sample-letter-gdpr-direct-marketing-objection/index.md
  content/en/blog/sample-letter-gdpr-erasure-request/index.md
  content/en/blog/sample-letter-gdpr-rectification-request/index.md
  static/downloads/musterschreiben-dsgvo-auskunft-datenanfragen.de.dotx
  static/downloads/musterschreiben-dsgvo-auskunft-datenanfragen.de.ott
  static/downloads/musterschreiben-dsgvo-auskunft-datenanfragen.de.pdf
  static/downloads/musterschreiben-dsgvo-auskunft-datenanfragen.de.txt
  static/downloads/musterschreiben-dsgvo-berichtigung-datenanfragen.de.dotx
  static/downloads/musterschreiben-dsgvo-berichtigung-datenanfragen.de.ott
  static/downloads/musterschreiben-dsgvo-berichtigung-datenanfragen.de.pdf
  static/downloads/musterschreiben-dsgvo-berichtigung-datenanfragen.de.txt
  static/downloads/musterschreiben-dsgvo-loeschung-datenanfragen.de.dotx
  static/downloads/musterschreiben-dsgvo-loeschung-datenanfragen.de.ott
  static/downloads/musterschreiben-dsgvo-loeschung-datenanfragen.de.pdf
  static/downloads/musterschreiben-dsgvo-loeschung-datenanfragen.de.txt
  static/downloads/musterschreiben-dsgvo-werbewiderspruch-datenanfragen.de.dotx
  static/downloads/musterschreiben-dsgvo-werbewiderspruch-datenanfragen.de.ott
  static/downloads/musterschreiben-dsgvo-werbewiderspruch-datenanfragen.de.pdf
  static/downloads/musterschreiben-dsgvo-werbewiderspruch-datenanfragen.de.txt
  static/downloads/sample-letter-gdpr-access-request-datarequests.org.dotx
  static/downloads/sample-letter-gdpr-access-request-datarequests.org.ott
  static/downloads/sample-letter-gdpr-access-request-datarequests.org.pdf
  static/downloads/sample-letter-gdpr-access-request-datarequests.org.txt
  static/downloads/sample-letter-gdpr-erasure-request-datarequests.org.dotx
  static/downloads/sample-letter-gdpr-erasure-request-datarequests.org.ott
  static/downloads/sample-letter-gdpr-erasure-request-datarequests.org.pdf
  static/downloads/sample-letter-gdpr-erasure-request-datarequests.org.txt
  static/downloads/sample-letter-gdpr-objection-request-datarequests.org.dotx
  static/downloads/sample-letter-gdpr-objection-request-datarequests.org.ott
  static/downloads/sample-letter-gdpr-objection-request-datarequests.org.pdf
  static/downloads/sample-letter-gdpr-objection-request-datarequests.org.txt
  static/downloads/sample-letter-gdpr-rectification-request-datarequests.org.dotx
  static/downloads/sample-letter-gdpr-rectification-request-datarequests.org.ott
  static/downloads/sample-letter-gdpr-rectification-request-datarequests.org.pdf
  static/downloads/sample-letter-gdpr-rectification-request-datarequests.org.txt
Labels: content

#334 Better link styling without inline-block
  src/styles/framework.scss
Labels: UI/UX

#338 Fixes #337: Error handler improvements
  src/Utility/errors.js
  src/error-handler.js
  src/suggest-edit.js
Labels: feature

#322 Implement various security headers
  _headers
  content/de/verein/event/okl-berlin-05-2020/index.md
  content/en/verein/event/okl-berlin-05-2020/index.md
  content/en/verein/event/okl-berlin-05-2020/poster.jpg
  deploy.sh
  layouts/_default/baseof.html
  webpack.common.js
Labels: security

#347 Made arrows in drop-down menus clickable + minor alignments
  src/Components/Generator/DynamicInputContainer.js
  src/Components/Generator/RequestForm.js
  src/styles/elements.scss
  src/styles/generator.scss
Labels: UI/UX, bug

#341 Added symbol for external links, fixes #287
  res/icons/external.svg
  src/i18n/README.md
  src/styles/framework.scss
  src/styles/icons.scss
  src/styles/variables.scss
Labels: UI/UX

#351 Load the pdfworker.js only if it is needed, fixes #330
  cypress/integration/components/generator.spec.js
  layouts/partials/scripts.html
  src/Utility/RequestLetter.js
Labels: optimization

#353 Fixes #352: Properly translate categories in the search
  src/Components/SearchBar.js
Labels: bug

#365 Extended external link selector to hopefully fix #360
  src/styles/variables.scss
Labels: bug

#370 Remove 'Membership fees' link from footer
  layouts/_default/baseof.html
  src/i18n/de.json
  src/i18n/en.json
  src/i18n/fr.json
  src/i18n/pt.json
Labels: content

#372 Speed optimizations part 1: Images
  layouts/partials/summary.html
  layouts/shortcodes/img.html
  src/Components/CommentsWidget.js
Labels: optimization

#376 Add page for our policy on compensated lectures (DE only)
  content/de/verein/compensated-lectures.md
  content/de/verein/transparency.md
  content/en/verein/transparency.md
Labels: content

#382 Update board details with Malte as our new assessor
  content/de/verein/board.md
  content/de/verein/transparency.md
  content/en/verein/board.md
  content/en/verein/transparency.md
  content/fr/verein/board.md
  content/fr/verein/transparency.md
  static/pgp/B713F012.asc
Labels: content

#383 Add the transcript for the OKL talk
  content/en/verein/event/okl-berlin-05-2020/index.md
Labels: content
