Repository datenanfragen/website, pull requests merged in 2020-10, with the labels that each got.

#408 Yandex Webmailer support
  src/Components/MailtoDropdown.js
  src/i18n/de.json
  src/i18n/en.json
  src/i18n/fr.json
  src/i18n/pt.json
Labels: feature

#411 Fixes #407: Update open-source overview page
  content/en/open-source.md
Labels: content

#443 Fix various link styling regressions from #426
  layouts/partials/embedded-video.html
  layouts/partials/summary-company.html
  layouts/partials/summary-sva.html
  layouts/supervisory-authority/single.html
  src/company-list.js
Labels: bug
