Repository datenanfragen/website, pull requests merged in 2020-11, with the labels that each got.

#487 Add tests for the ActWidget, fixes #472
  cypress/integration/components/actwidget.spec.js
Labels: testing

#488 Fixed links on /suggest, added more details, fixes #474
  content/de/suggest.md
Labels: bug, content, discussion

#492 Add alt tags to images
  content/de/act/ada-health/index.md
  content/de/act/deliveroo.md
  content/de/blog/gdpr-cheat-sheet.md
  content/de/blog/hacktoberfest-2019/index.md
  content/de/blog/hacktoberfest-2020/index.md
  content/de/blog/supervisory-authorities/index.md
  content/de/open-source.md
  content/de/thanks.md
  content/de/verein/transparency.md
  content/en/blog/gdpr-cheat-sheet.md
  content/en/blog/hacktoberfest-2019/index.md
  content/en/blog/hacktoberfest-2020/index.md
  content/en/blog/supervisory-authorities/index.md
  content/en/open-source.md
  content/en/thanks.md
  content/en/verein/transparency.md
  content/fr/blog/supervisory-authorities/index.md
  content/fr/open-source.md
  content/fr/thanks.md
  content/pt/open-source.md
  layouts/404.html
  layouts/verein/list.html
  src/i18n/de.json
  src/i18n/en.json
Labels: a11y

#499 Add generator tests: Machine-readable checkbox and company loading
  cypress/integration/components/generator.spec.js
Labels: testing

#500 Move signature styling into elements.scss
  assets/styles/elements.scss
  assets/styles/generator.scss
Labels: UI/UX, bug

#513 Skip components/svafinder/generator-complaints test in prod
  cypress/integration/components/svafinder.spec.js
Labels: bug, testing

#508 Add test for /suggest
  cypress/integration/use-cases/suggest.spec.js
Labels: testing
