Repository datenanfragen/website, pull requests merged in 2021-12, with the labels that each got.

#829 Various linter improvements
  .circleci/config.yml
  .eslintrc.js
  .nvmrc
  .stylelintrc
  assets/styles/color-palette.scss
  assets/styles/elements.scss
  assets/styles/framework.scss
  assets/styles/main.scss
  assets/styles/variables.scss
  package.json
  prettier.config.js
  src/Components/SearchBar.js
  src/Components/SvaFinder.js
  src/Utility/Privacy.js
  src/general.js
  src/generator.js
  yarn.lock
Labels: testing

#831 Improve Hugo build speed by optimizing related company computation
  layouts/partials/related-companies.html
Labels: optimization

#761 docs: fix some wrong translations/typos on the PT lang
  src/i18n/pt.json
Labels: hacktoberfest-accepted

#789 Hide fixed fields with same value/desc
  src/Components/Generator/DynamicInputContainer.js
Labels: hacktoberfest-accepted

#776 Made links more accessible in Search Suggestions
  assets/styles/elements.scss
  src/Components/SearchBar.js
Labels: hacktoberfest-accepted

#835 Fix bugs introduced by #776
  assets/styles/elements.scss
  src/Components/SearchBar.js
Labels: bug
