Repository datenanfragen/website, pull requests merged in 2021-01, with the labels that each got.

#527 add test for the information block
  cypress/integration/components/generator.spec.js
Labels: testing

#530 enable comments for supervisory-authority pages
  layouts/supervisory-authority/single.html
Labels: feature

#535 Add Berni's post on erasure for advertising companies
  config/_default/params.toml
  content/de/blog/datenloeschung-bei-werbetreibenden/datenloeschung-werbetreibende.jpg
  content/de/blog/datenloeschung-bei-werbetreibenden/index.md
Labels: content

#540 Test if signature field is shown/hidden properly
  cypress/integration/components/generator.spec.js
Labels: testing
