Repository datenanfragen/website, pull requests merged in 2021-05, with the labels that each got.

#595 WIP: add act page for lieferando drivers
  content/de/act/lieferando/index.md
  content/de/act/lieferando/lieferando-ueberwachung.jpg
Labels: content

#599 Fixes #507: Require date in generator
  cypress/integration/old-bugs/no-empty-date-in-generator.spec.js
  src/Components/Generator/RequestForm.js
Labels: bug

#598 Fixes #525: Make generator 'recipient' field hint at transport medium
  src/Components/Generator/RecipientInput.js
  src/i18n/de.json
  src/i18n/en.json
Labels: UI/UX

#602 Closes #504: Fix cut-off 'required' asterisk
  assets/styles/elements.scss
Labels: bug

#606 Fix 'no-empty-date-in-generator' test failing in production
  cypress/integration/old-bugs/no-empty-date-in-generator.spec.js
Labels: bug, testing
