Repository datenanfragen/website, pull requests merged in 2021-09, with the labels that each got.

#666 Fixes #656: Ignore errors from extensions in error handler
  src/error-handler.js
Labels: UI/UX

#447 Add aggregate ratings to comments
  layouts/company/single.html
  src/Components/CommentsWidget.js
  src/i18n/de.json
  src/i18n/en.json
Labels: hacktoberfest-accepted

#590 Company list: Use anchors as search suggestions (fixes #544)
  assets/styles/elements.scss
  src/Components/SearchBar.js
  src/company-list.js
Labels: cleanup, feature, a11y

#667 Fixes #620: Don't include Hugo translations in JS bundle
  src/Utility/webpack-i18n-loader.js
Labels: optimization

#684 Fix double slash in SearchBar links
  src/Components/SearchBar.js
Labels: bug
